// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 31/01/2025, 08:23:32
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/plugins/**/*.{js,ts,mjs}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/composables/**/*.{js,ts,mjs}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/utils/**/*.{js,ts,mjs}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/OneDrive/Desktop/proficient/kid-dance-demo/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;