// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/27/2025, 12:16:30 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/OWNER/Desktop/nuxt-test-run/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/plugins/**/*.{js,ts,mjs}","C:/Users/OWNER/Desktop/nuxt-test-run/composables/**/*.{js,ts,mjs}","C:/Users/OWNER/Desktop/nuxt-test-run/utils/**/*.{js,ts,mjs}","C:/Users/OWNER/Desktop/nuxt-test-run/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/OWNER/Desktop/nuxt-test-run/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;